version: "3"
services:
 tado_aa:
  restart: always
  container_name: tado-container
  image: tado_aa_geo:latest
  environment:
   - GEOFENCING=False
   - TZ=yourtimezone.e.g<Europe/Berlin>
  volumes:
    - tado_data:/tado_token/

volumes:
  tado_data:
    driver: local